import { packageVersion } from "../../core/package-version.js";

export function renderClaudePreToolUseHook(): string {
  return `#!/usr/bin/env node
// Generated by Visp Kit. Blocks Edit/Write tool calls that bypass the Visp implement gate.
// Wire into Claude Code via .claude/settings.json (see .visp/hooks/README.md).
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import path from "node:path";

function allow() {
  process.exit(0);
}

function block(reason) {
  writeFileSync(2, \`\${reason}\\n\`);
  process.exit(2);
}

function baselineCacheIssue(baseline) {
  const cache = baseline?.cacheKey;
  if (
    typeof cache !== "object" ||
    cache === null ||
    !Array.isArray(cache.lockfiles) ||
    !Array.isArray(cache.configurations) ||
    !Array.isArray(cache.providers) ||
    !Array.isArray(cache.runtimes)
  ) {
    return "the baseline cache key is malformed";
  }
  if (!Array.isArray(baseline?.providerRuns)) {
    return "the baseline provider evidence is missing";
  }
  const requiredProviders = cache.providers
    .map((provider) => \`\${provider?.id}@\${provider?.version}\`)
    .sort();
  const providerRuns = baseline.providerRuns
    .map((run) => \`\${run?.provider?.id}@\${run?.provider?.version}\`)
    .sort();
  if (
    baseline.providerRuns.length === 0 ||
    baseline.providerRuns.some((run) => run?.status !== "passed") ||
    new Set(providerRuns).size !== providerRuns.length ||
    JSON.stringify(providerRuns) !== JSON.stringify(requiredProviders)
  ) {
    return "the baseline provider evidence is incomplete";
  }
  if (cache.platform !== process.platform || cache.architecture !== process.arch) {
    return "the operating system or architecture changed";
  }
  const nodeRuntime = cache.runtimes.find((runtime) => runtime?.id === "node");
  const nodeMajor = Number.parseInt(process.versions.node.split(".")[0] ?? "0", 10);
  if (nodeRuntime?.major !== nodeMajor) return "the Node.js major version changed";

  const configuredRuntimes = cache.runtimes.filter((runtime) => runtime?.id !== "node");
  if (configuredRuntimes.length > 0) {
    let configured;
    try {
      const manifest = JSON.parse(readFileSync(path.join(projectDir, "package.json"), "utf8"));
      const match = /^([A-Za-z0-9._-]+)@(\\d+)/u.exec(manifest.packageManager ?? "");
      configured =
        match === null ? undefined : { id: match[1], major: Number.parseInt(match[2], 10) };
    } catch {
      configured = undefined;
    }
    if (
      configuredRuntimes.length !== 1 ||
      configured === undefined ||
      configuredRuntimes[0].id !== configured.id ||
      configuredRuntimes[0].major !== configured.major
    ) {
      return "the configured package-manager major version changed";
    }
  }

  if (cache.baseCommit?.status === "captured") {
    try {
      const currentCommit = execFileSync("git", ["rev-parse", "HEAD"], {
        cwd: projectDir,
        encoding: "utf8"
      }).trim();
      if (currentCommit !== cache.baseCommit.commit) return "the base commit changed";
    } catch {
      return "the base commit cannot be verified";
    }
  }

  for (const entry of [...cache.lockfiles, ...cache.configurations]) {
    if (
      typeof entry?.path !== "string" ||
      typeof entry?.sha256 !== "string"
    ) {
      return "a cache input binding is malformed";
    }
    const inputPath = path.resolve(projectDir, entry.path);
    const relative = path.relative(projectDir, inputPath);
    if (relative === "" || relative === ".." || relative.startsWith(\`..\${path.sep}\`)) {
      return "a cache input path escapes the project";
    }
    try {
      const currentHash =
        \`sha256:\${createHash("sha256").update(readFileSync(inputPath)).digest("hex")}\`;
      if (currentHash !== entry.sha256) return \`cache input \${entry.path} changed\`;
    } catch {
      return \`cache input \${entry.path} is missing or unreadable\`;
    }
  }
  return null;
}

let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  // Not a well-formed Claude hook event; blocking here would break every
  // tool call in the session, including outside Visp projects.
  allow();
}
if (typeof input !== "object" || input === null) allow();

const editTools = new Set(["Edit", "Write", "MultiEdit", "NotebookEdit"]);
if (!editTools.has(input.tool_name ?? "")) allow();

const filePath = input.tool_input?.file_path ?? input.tool_input?.notebook_path ?? "";
if (filePath === "") allow();

const projectDir = input.cwd ?? process.cwd();
const vispDir = path.join(projectDir, ".visp");
if (!existsSync(vispDir)) allow();

const rel = path.relative(projectDir, path.resolve(projectDir, filePath));
if (rel === "" || rel.startsWith("..")) allow();

const normalized = rel.split(path.sep).join("/");
if (normalized === ".visp" || normalized.startsWith(".visp/")) allow();

const policyPath = path.join(vispDir, "policy.json");
// A deleted policy leaves enforcement state exactly as unknown as a corrupted
// one, so an initialized project fails closed either way. Deleting the file
// must not be the one tampering path that succeeds. A bare .visp/ directory
// that was never initialized still allows, so non-Visp checkouts and
// partially-set-up projects are unaffected.
if (!existsSync(policyPath)) {
  if (existsSync(path.join(vispDir, "project.json"))) {
    block(
      "Visp gate: .visp/policy.json is missing from an initialized Visp project, so " +
        "enforcement state is unknown. Restore it or run \`visp policy init\` before editing."
    );
  }
  allow();
}

let policy;
try {
  policy = JSON.parse(readFileSync(policyPath, "utf8"));
} catch {
  block(
    "Visp gate: .visp/policy.json exists but cannot be read or parsed, so strictness " +
      "is unknown. Fix the policy (\`visp policy validate\`) before editing."
  );
}

const knownModes = new Set(["relaxed", "standard", "strict", "locked"]);
if (typeof policy !== "object" || policy === null || !knownModes.has(policy.strictnessMode)) {
  block(
    "Visp gate: .visp/policy.json has an unknown strictnessMode, so enforcement state " +
      "is unknown. Fix the policy (\`visp policy validate\`) before editing."
  );
}
if (policy.strictnessMode !== "strict" && policy.strictnessMode !== "locked") allow();

// Active authorizations: per-task markers in the directory plus the legacy
// single marker. Any unreadable marker fails closed.
const markerDir = path.join(vispDir, "state", "implement-allowed");
const legacyMarkerPath = path.join(vispDir, "state", "implement-allowed.json");
const markers = [];
if (existsSync(markerDir)) {
  for (const name of readdirSync(markerDir)) {
    if (!name.endsWith(".json")) continue;
    let candidate;
    try {
      candidate = JSON.parse(readFileSync(path.join(markerDir, name), "utf8"));
    } catch {
      block(
        \`Visp gate: implement authorization marker \${name} is unreadable. \` +
          "Re-run \`visp gate implement --task <task-id>\`."
      );
    }
    if (typeof candidate === "object" && candidate !== null) markers.push(candidate);
  }
}
if (existsSync(legacyMarkerPath)) {
  let legacy;
  try {
    legacy = JSON.parse(readFileSync(legacyMarkerPath, "utf8"));
  } catch {
    block(
      "Visp gate: the implement authorization marker is unreadable. " +
        "Re-run \`visp gate implement --task <task-id>\`."
    );
  }
  if (
    typeof legacy === "object" &&
    legacy !== null &&
    !markers.some((marker) => marker.taskId === legacy.taskId)
  ) {
    markers.push(legacy);
  }
}

if (markers.length === 0) {
  block(
    "Visp gate: no implement authorization found. Run \`visp gate implement --task <task-id>\` " +
      "and only edit code after it reports allowed."
  );
}

for (const marker of markers) {
  const authorization = marker.oracleAuthorization;
  if (authorization === undefined) continue;
  if (
    typeof authorization !== "object" ||
    authorization === null ||
    typeof authorization.lockPath !== "string" ||
    typeof authorization.lockHash !== "string" ||
    typeof authorization.lockFileSha256 !== "string"
  ) {
    block(\`Visp gate: oracle authorization for task \${marker.taskId} is malformed.\`);
  }
  const lockPath = path.resolve(projectDir, authorization.lockPath);
  const lockRelative = path.relative(projectDir, lockPath);
  if (lockRelative === "" || lockRelative === ".." || lockRelative.startsWith(\`..\${path.sep}\`)) {
    block(\`Visp gate: oracle lock path for task \${marker.taskId} escapes the project.\`);
  }
  let lockText;
  let lock;
  try {
    lockText = readFileSync(lockPath, "utf8");
    lock = JSON.parse(lockText);
  } catch {
    block(
      \`Visp gate: oracle lock for task \${marker.taskId} is missing or unreadable. \` +
        "Re-run \`visp gate implement --task <task-id>\`."
    );
  }
  const fileHash = \`sha256:\${createHash("sha256").update(lockText, "utf8").digest("hex")}\`;
  if (fileHash !== authorization.lockFileSha256 || lock?.lockHash !== authorization.lockHash) {
    block(
      \`Visp gate: oracle lock for task \${marker.taskId} changed after authorization. \` +
        "Re-run \`visp oracle lock --task <task-id>\` and the implement gate."
      );
  }
  if (lock?.baselineEvidence === undefined) {
    block(\`Visp gate: oracle authorization for task \${marker.taskId} has no baseline evidence.\`);
  } else {
    const baselinePath = path.resolve(projectDir, lock.baselineEvidence.path ?? "");
    const baselineRelative = path.relative(projectDir, baselinePath);
    if (
      baselineRelative === "" ||
      baselineRelative === ".." ||
      baselineRelative.startsWith(\`..\${path.sep}\`)
    ) {
      block(\`Visp gate: baseline evidence path for task \${marker.taskId} is invalid.\`);
    }
    let baselineText;
    let baseline;
    try {
      baselineText = readFileSync(baselinePath, "utf8");
      baseline = JSON.parse(baselineText);
    } catch {
      block(\`Visp gate: baseline evidence for task \${marker.taskId} is missing or unreadable.\`);
    }
    const baselineHash =
      \`sha256:\${createHash("sha256").update(baselineText, "utf8").digest("hex")}\`;
    if (baselineHash !== lock.baselineEvidence.sha256) {
      block(\`Visp gate: baseline evidence for task \${marker.taskId} changed after locking.\`);
    }
    const issue = baselineCacheIssue(baseline);
    if (issue !== null) {
      block(\`Visp gate: baseline evidence for task \${marker.taskId} is stale: \${issue}.\`);
    }
  }
}

// Forbidden wins across every active task.
for (const marker of markers) {
  if ((marker.forbiddenFiles ?? []).includes(normalized)) {
    block(\`Visp gate: \${normalized} is forbidden for task \${marker.taskId}. Do not edit it.\`);
  }
}

const scopes = markers.map((marker) => [
  ...(marker.allowedFiles ?? []),
  ...(marker.expectedFiles ?? [])
]);
const unrestricted = scopes.some((scope) => scope.length === 0);
const union = scopes.flat();
if (!unrestricted && !union.includes(normalized)) {
  const taskIds = markers.map((marker) => marker.taskId).join(", ");
  block(
    \`Visp gate: \${normalized} is outside the allowed files for active tasks \${taskIds} \` +
      \`(allowed: \${union.join(", ")}). Edit only allowed files or update the task definitions.\`
  );
}

allow();
`;
}

export function renderPreCommitCheck(): string {
  return `#!/usr/bin/env node
// Generated by Visp Kit. Pre-commit evidence check for staged source files.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

function allow() {
  process.exit(0);
}

function block(reason) {
  writeFileSync(2, \`\${reason}\\n\`);
  process.exit(1);
}

const projectDir = process.cwd();
const vispDir = path.join(projectDir, ".visp");
if (!existsSync(vispDir)) allow();

const policyPath = path.join(vispDir, "policy.json");
// A deleted policy leaves enforcement state exactly as unknown as a corrupted
// one, so an initialized project fails closed either way. Deleting the file
// must not be the one tampering path that succeeds. A bare .visp/ directory
// that was never initialized still allows, so non-Visp checkouts and
// partially-set-up projects are unaffected.
if (!existsSync(policyPath)) {
  if (existsSync(path.join(vispDir, "project.json"))) {
    block(
      "Visp: .visp/policy.json is missing from an initialized Visp project, so " +
        "enforcement state is unknown. Restore it or run \`visp policy init\` before committing."
    );
  }
  allow();
}

let policy;
try {
  policy = JSON.parse(readFileSync(policyPath, "utf8"));
} catch {
  block(
    "Visp: .visp/policy.json exists but cannot be read or parsed, so strictness is " +
      "unknown. Fix the policy (\`visp policy validate\`) before committing."
  );
}

const knownModes = new Set(["relaxed", "standard", "strict", "locked"]);
if (typeof policy !== "object" || policy === null || !knownModes.has(policy.strictnessMode)) {
  block(
    "Visp: .visp/policy.json has an unknown strictnessMode, so enforcement state is " +
      "unknown. Fix the policy (\`visp policy validate\`) before committing."
  );
}

const enforce = policy.strictnessMode === "strict" || policy.strictnessMode === "locked";

let staged;
try {
  staged = execFileSync("git", ["diff", "--cached", "--name-only"], { encoding: "utf8" })
    .split(/\\r?\\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
} catch {
  const message =
    "Visp: pre-commit check could not read staged files from git, so task scope is unknown.";
  if (enforce) block(message);
  writeFileSync(2, \`Warning: \${message}\\n\`);
  allow();
}

const sourceFiles = staged.filter((file) => !file.startsWith(".visp/"));
if (sourceFiles.length === 0) allow();

// Active authorizations: per-task markers in the directory plus the legacy
// single marker. Any unreadable marker fails closed when enforcing.
const markerDir = path.join(vispDir, "state", "implement-allowed");
const legacyMarkerPath = path.join(vispDir, "state", "implement-allowed.json");
const markers = [];

function unreadableMarker(name) {
  const message =
    \`Visp: implement authorization marker \${name} is unreadable, so task scope is unknown. \` +
    "Re-run \`visp gate implement --task <task-id>\` before committing.";
  if (enforce) block(message);
  writeFileSync(2, \`Warning: \${message}\\n\`);
}

function baselineCacheIssue(baseline) {
  const cache = baseline?.cacheKey;
  if (
    typeof cache !== "object" ||
    cache === null ||
    !Array.isArray(cache.lockfiles) ||
    !Array.isArray(cache.configurations) ||
    !Array.isArray(cache.providers) ||
    !Array.isArray(cache.runtimes)
  ) {
    return "the baseline cache key is malformed";
  }
  if (!Array.isArray(baseline?.providerRuns)) {
    return "the baseline provider evidence is missing";
  }
  const requiredProviders = cache.providers
    .map((provider) => \`\${provider?.id}@\${provider?.version}\`)
    .sort();
  const providerRuns = baseline.providerRuns
    .map((run) => \`\${run?.provider?.id}@\${run?.provider?.version}\`)
    .sort();
  if (
    baseline.providerRuns.length === 0 ||
    baseline.providerRuns.some((run) => run?.status !== "passed") ||
    new Set(providerRuns).size !== providerRuns.length ||
    JSON.stringify(providerRuns) !== JSON.stringify(requiredProviders)
  ) {
    return "the baseline provider evidence is incomplete";
  }
  if (cache.platform !== process.platform || cache.architecture !== process.arch) {
    return "the operating system or architecture changed";
  }
  const nodeRuntime = cache.runtimes.find((runtime) => runtime?.id === "node");
  const nodeMajor = Number.parseInt(process.versions.node.split(".")[0] ?? "0", 10);
  if (nodeRuntime?.major !== nodeMajor) return "the Node.js major version changed";

  const configuredRuntimes = cache.runtimes.filter((runtime) => runtime?.id !== "node");
  if (configuredRuntimes.length > 0) {
    let configured;
    try {
      const manifest = JSON.parse(readFileSync(path.join(projectDir, "package.json"), "utf8"));
      const match = /^([A-Za-z0-9._-]+)@(\\d+)/u.exec(manifest.packageManager ?? "");
      configured =
        match === null ? undefined : { id: match[1], major: Number.parseInt(match[2], 10) };
    } catch {
      configured = undefined;
    }
    if (
      configuredRuntimes.length !== 1 ||
      configured === undefined ||
      configuredRuntimes[0].id !== configured.id ||
      configuredRuntimes[0].major !== configured.major
    ) {
      return "the configured package-manager major version changed";
    }
  }

  if (cache.baseCommit?.status === "captured") {
    try {
      const currentCommit = execFileSync("git", ["rev-parse", "HEAD"], {
        cwd: projectDir,
        encoding: "utf8"
      }).trim();
      if (currentCommit !== cache.baseCommit.commit) return "the base commit changed";
    } catch {
      return "the base commit cannot be verified";
    }
  }

  for (const entry of [...cache.lockfiles, ...cache.configurations]) {
    if (typeof entry?.path !== "string" || typeof entry?.sha256 !== "string") {
      return "a cache input binding is malformed";
    }
    const inputPath = path.resolve(projectDir, entry.path);
    const relative = path.relative(projectDir, inputPath);
    if (relative === "" || relative === ".." || relative.startsWith(\`..\${path.sep}\`)) {
      return "a cache input path escapes the project";
    }
    try {
      const currentHash =
        \`sha256:\${createHash("sha256").update(readFileSync(inputPath)).digest("hex")}\`;
      if (currentHash !== entry.sha256) return \`cache input \${entry.path} changed\`;
    } catch {
      return \`cache input \${entry.path} is missing or unreadable\`;
    }
  }
  return null;
}

if (existsSync(markerDir)) {
  for (const name of readdirSync(markerDir)) {
    if (!name.endsWith(".json")) continue;
    try {
      const candidate = JSON.parse(readFileSync(path.join(markerDir, name), "utf8"));
      if (typeof candidate === "object" && candidate !== null) markers.push(candidate);
    } catch {
      unreadableMarker(name);
    }
  }
}
if (existsSync(legacyMarkerPath)) {
  try {
    const legacy = JSON.parse(readFileSync(legacyMarkerPath, "utf8"));
    if (
      typeof legacy === "object" &&
      legacy !== null &&
      !markers.some((marker) => marker.taskId === legacy.taskId)
    ) {
      markers.push(legacy);
    }
  } catch {
    unreadableMarker("implement-allowed.json");
  }
}

if (markers.length === 0) {
  const message =
    "Visp: staged source changes have no implement authorization " +
    "(.visp/state/implement-allowed.json missing). " +
    "Run \`visp gate implement --task <task-id>\` and \`visp done --task <task-id>\` before committing.";
  if (enforce) block(message);
  writeFileSync(2, \`Warning: \${message}\\n\`);
  allow();
}

for (const marker of markers) {
  const authorization = marker.oracleAuthorization;
  if (authorization === undefined) continue;
  const invalid = (reason) => {
    const message =
      \`Visp: oracle authorization for task \${marker.taskId} is invalid: \${reason}. \` +
      "Re-run \`visp oracle lock --task <task-id>\` and the implement gate.";
    if (enforce) block(message);
    writeFileSync(2, \`Warning: \${message}\\n\`);
  };
  if (
    typeof authorization !== "object" ||
    authorization === null ||
    typeof authorization.lockPath !== "string" ||
    typeof authorization.lockHash !== "string" ||
    typeof authorization.lockFileSha256 !== "string"
  ) {
    invalid("the marker binding is malformed");
    continue;
  }
  const lockPath = path.resolve(projectDir, authorization.lockPath);
  const lockRelative = path.relative(projectDir, lockPath);
  if (lockRelative === "" || lockRelative === ".." || lockRelative.startsWith(\`..\${path.sep}\`)) {
    invalid("the lock path escapes the project");
    continue;
  }
  let lockText;
  let lock;
  try {
    lockText = readFileSync(lockPath, "utf8");
    lock = JSON.parse(lockText);
  } catch {
    invalid("the lock is missing or unreadable");
    continue;
  }
  const fileHash = \`sha256:\${createHash("sha256").update(lockText, "utf8").digest("hex")}\`;
  if (fileHash !== authorization.lockFileSha256 || lock?.lockHash !== authorization.lockHash) {
    invalid("the lock changed after authorization");
    continue;
  }
  if (lock?.baselineEvidence === undefined) {
    invalid("the oracle lock has no baseline evidence");
    continue;
  } else {
    const baselinePath = path.resolve(projectDir, lock.baselineEvidence.path ?? "");
    const baselineRelative = path.relative(projectDir, baselinePath);
    if (
      baselineRelative === "" ||
      baselineRelative === ".." ||
      baselineRelative.startsWith(\`..\${path.sep}\`)
    ) {
      invalid("the baseline evidence path is invalid");
      continue;
    }
    let baselineText;
    let baseline;
    try {
      baselineText = readFileSync(baselinePath, "utf8");
      baseline = JSON.parse(baselineText);
    } catch {
      invalid("the baseline evidence is missing or unreadable");
      continue;
    }
    const baselineHash =
      \`sha256:\${createHash("sha256").update(baselineText, "utf8").digest("hex")}\`;
    if (baselineHash !== lock.baselineEvidence.sha256) {
      invalid("the baseline evidence changed after locking");
      continue;
    }
    const issue = baselineCacheIssue(baseline);
    if (issue !== null) {
      invalid(\`the baseline evidence is stale: \${issue}\`);
    }
  }
}

const scopes = markers.map((marker) => [
  ...(marker.allowedFiles ?? []),
  ...(marker.expectedFiles ?? [])
]);
const unrestricted = scopes.some((scope) => scope.length === 0);
const union = scopes.flat();
const forbidden = markers.flatMap((marker) => marker.forbiddenFiles ?? []);
const outOfScope = sourceFiles.filter(
  (file) => forbidden.includes(file) || (!unrestricted && !union.includes(file))
);

if (outOfScope.length > 0) {
  const taskIds = markers.map((marker) => marker.taskId).join(", ");
  const message =
    \`Visp: staged files are outside the scope of active tasks \${taskIds}: \` +
    \`\${outOfScope.join(", ")}. Allowed: \${union.join(", ") || "none declared"}.\`;
  if (enforce) block(message);
  writeFileSync(2, \`Warning: \${message}\\n\`);
}

allow();
`;
}

export function renderPreCommitWrapper(): string {
  return `#!/usr/bin/env bash
# Generated by Visp Kit (visp hooks git). Delegates to the Visp pre-commit check.
set -euo pipefail

if [ -f .visp/hooks/visp-pre-commit.mjs ]; then
  node .visp/hooks/visp-pre-commit.mjs
fi
`;
}

export function renderGithubEvidenceWorkflow(version: string = packageVersion()): string {
  // Pin the Kit version that generated this workflow. An evidence gate that
  // installs whatever `latest` resolves to cannot produce reproducible
  // verdicts, and silently changes enforcement on an unrelated release.
  // Re-run `visp hooks ci --force` after upgrading Visp Kit.
  return `name: visp-evidence

on:
  pull_request:

jobs:
  evidence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Visp Kit
        run: npm install -g visp-kit@${version}
      - name: Validate policy
        run: visp policy validate --json
      - name: Check PR gate
        run: visp gate pr --json
`;
}

export function renderClaudeSettingsSnippet(): string {
  return JSON.stringify(
    {
      hooks: {
        PreToolUse: [
          {
            matcher: "Edit|Write|MultiEdit|NotebookEdit",
            hooks: [
              {
                type: "command",
                command: "node .visp/hooks/claude-pretooluse.mjs"
              }
            ]
          }
        ]
      }
    },
    null,
    2
  );
}

export function renderHooksReadme(): string {
  return `# Visp Kit Enforcement Hooks

These files make Visp gates mechanical instead of advisory. They only enforce
when \`.visp/policy.json\` strictness is \`strict\` or \`locked\`; other modes warn
or stay silent.

Enforcement fails closed: if \`.visp/policy.json\` exists but cannot be parsed,
or declares an unknown strictness mode, the hooks block instead of silently
allowing, because the enforcement state is unknown. A missing policy file
falls back to the non-enforcing \`standard\` default.

## Claude Code PreToolUse hook

\`claude-pretooluse.mjs\` blocks Edit/Write tool calls before
\`visp gate implement --task <task-id>\` has allowed implementation, and blocks
edits outside the task's allowed files.

Enable it by merging this into \`.claude/settings.json\` (or
\`.claude/settings.local.json\`):

\`\`\`json
${renderClaudeSettingsSnippet()}
\`\`\`

## Git pre-commit hook

\`visp-pre-commit.mjs\` checks staged source files against the active task's
implement authorization. Install the wrapper with:

\`\`\`bash
visp hooks git
\`\`\`

## CI evidence check

Generate a GitHub Actions workflow that validates policy and the PR gate on
every pull request:

\`\`\`bash
visp hooks ci
\`\`\`

## How authorization works

\`visp gate implement --task <task-id>\` writes a per-task marker under
\`.visp/state/implement-allowed/<task-id>.json\` (plus the legacy
\`.visp/state/implement-allowed.json\` for hooks generated before per-task
markers existed) when the gate allows implementation. Multiple tasks can hold
authorizations at once; the gate blocks a second task whose file scope
overlaps an active one. \`visp done --task <task-id>\` clears that task's
marker when every step passes, and a blocked implement gate clears it too.

Hooks read every active marker: a file is editable when any active task allows
it and no active task forbids it (forbidden wins). Hooks never call the
network. Markers are per-checkout state — each git worktree has its own — so
parallel agents in separate worktrees do not share authorizations.
`;
}
