export function renderClaudePreToolUseHook(): string {
  return `#!/usr/bin/env node
// Generated by Visp Kit. Blocks Edit/Write tool calls that bypass the Visp implement gate.
// Wire into Claude Code via .claude/settings.json (see .visp/hooks/README.md).
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

function allow() {
  process.exit(0);
}

function block(reason) {
  writeFileSync(2, \`\${reason}\\n\`);
  process.exit(2);
}

let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  // Not a well-formed Claude hook event; blocking here would break every
  // tool call in the session, including outside Visp projects.
  allow();
}
if (typeof input !== "object" || input === null) allow();

const editTools = new Set(["Edit", "Write", "MultiEdit", "NotebookEdit"]);
if (!editTools.has(input.tool_name ?? "")) allow();

const filePath = input.tool_input?.file_path ?? input.tool_input?.notebook_path ?? "";
if (filePath === "") allow();

const projectDir = input.cwd ?? process.cwd();
const vispDir = path.join(projectDir, ".visp");
if (!existsSync(vispDir)) allow();

const rel = path.relative(projectDir, path.resolve(projectDir, filePath));
if (rel === "" || rel.startsWith("..")) allow();

const normalized = rel.split(path.sep).join("/");
if (normalized === ".visp" || normalized.startsWith(".visp/")) allow();

const policyPath = path.join(vispDir, "policy.json");
// Missing policy means the default "standard" strictness, which does not
// enforce. An unreadable or invalid policy in a Visp project must fail
// closed: enforcement state is unknown.
if (!existsSync(policyPath)) allow();

let policy;
try {
  policy = JSON.parse(readFileSync(policyPath, "utf8"));
} catch {
  block(
    "Visp gate: .visp/policy.json exists but cannot be read or parsed, so strictness " +
      "is unknown. Fix the policy (\`visp policy validate\`) before editing."
  );
}

const knownModes = new Set(["relaxed", "standard", "strict", "locked"]);
if (typeof policy !== "object" || policy === null || !knownModes.has(policy.strictnessMode)) {
  block(
    "Visp gate: .visp/policy.json has an unknown strictnessMode, so enforcement state " +
      "is unknown. Fix the policy (\`visp policy validate\`) before editing."
  );
}
if (policy.strictnessMode !== "strict" && policy.strictnessMode !== "locked") allow();

// Active authorizations: per-task markers in the directory plus the legacy
// single marker. Any unreadable marker fails closed.
const markerDir = path.join(vispDir, "state", "implement-allowed");
const legacyMarkerPath = path.join(vispDir, "state", "implement-allowed.json");
const markers = [];
if (existsSync(markerDir)) {
  for (const name of readdirSync(markerDir)) {
    if (!name.endsWith(".json")) continue;
    let candidate;
    try {
      candidate = JSON.parse(readFileSync(path.join(markerDir, name), "utf8"));
    } catch {
      block(
        \`Visp gate: implement authorization marker \${name} is unreadable. \` +
          "Re-run \`visp gate implement --task <task-id>\`."
      );
    }
    if (typeof candidate === "object" && candidate !== null) markers.push(candidate);
  }
}
if (existsSync(legacyMarkerPath)) {
  let legacy;
  try {
    legacy = JSON.parse(readFileSync(legacyMarkerPath, "utf8"));
  } catch {
    block(
      "Visp gate: the implement authorization marker is unreadable. " +
        "Re-run \`visp gate implement --task <task-id>\`."
    );
  }
  if (
    typeof legacy === "object" &&
    legacy !== null &&
    !markers.some((marker) => marker.taskId === legacy.taskId)
  ) {
    markers.push(legacy);
  }
}

if (markers.length === 0) {
  block(
    "Visp gate: no implement authorization found. Run \`visp gate implement --task <task-id>\` " +
      "and only edit code after it reports allowed."
  );
}

// Forbidden wins across every active task.
for (const marker of markers) {
  if ((marker.forbiddenFiles ?? []).includes(normalized)) {
    block(\`Visp gate: \${normalized} is forbidden for task \${marker.taskId}. Do not edit it.\`);
  }
}

const scopes = markers.map((marker) => [
  ...(marker.allowedFiles ?? []),
  ...(marker.expectedFiles ?? [])
]);
const unrestricted = scopes.some((scope) => scope.length === 0);
const union = scopes.flat();
if (!unrestricted && !union.includes(normalized)) {
  const taskIds = markers.map((marker) => marker.taskId).join(", ");
  block(
    \`Visp gate: \${normalized} is outside the allowed files for active tasks \${taskIds} \` +
      \`(allowed: \${union.join(", ")}). Edit only allowed files or update the task definitions.\`
  );
}

allow();
`;
}

export function renderPreCommitCheck(): string {
  return `#!/usr/bin/env node
// Generated by Visp Kit. Pre-commit evidence check for staged source files.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import path from "node:path";

function allow() {
  process.exit(0);
}

function block(reason) {
  writeFileSync(2, \`\${reason}\\n\`);
  process.exit(1);
}

const projectDir = process.cwd();
const vispDir = path.join(projectDir, ".visp");
if (!existsSync(vispDir)) allow();

const policyPath = path.join(vispDir, "policy.json");
// Missing policy means the default "standard" strictness, which does not
// enforce. An unreadable or invalid policy must fail closed: enforcement
// state is unknown.
if (!existsSync(policyPath)) allow();

let policy;
try {
  policy = JSON.parse(readFileSync(policyPath, "utf8"));
} catch {
  block(
    "Visp: .visp/policy.json exists but cannot be read or parsed, so strictness is " +
      "unknown. Fix the policy (\`visp policy validate\`) before committing."
  );
}

const knownModes = new Set(["relaxed", "standard", "strict", "locked"]);
if (typeof policy !== "object" || policy === null || !knownModes.has(policy.strictnessMode)) {
  block(
    "Visp: .visp/policy.json has an unknown strictnessMode, so enforcement state is " +
      "unknown. Fix the policy (\`visp policy validate\`) before committing."
  );
}

const enforce = policy.strictnessMode === "strict" || policy.strictnessMode === "locked";

let staged;
try {
  staged = execFileSync("git", ["diff", "--cached", "--name-only"], { encoding: "utf8" })
    .split(/\\r?\\n/)
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
} catch {
  const message =
    "Visp: pre-commit check could not read staged files from git, so task scope is unknown.";
  if (enforce) block(message);
  writeFileSync(2, \`Warning: \${message}\\n\`);
  allow();
}

const sourceFiles = staged.filter((file) => !file.startsWith(".visp/"));
if (sourceFiles.length === 0) allow();

// Active authorizations: per-task markers in the directory plus the legacy
// single marker. Any unreadable marker fails closed when enforcing.
const markerDir = path.join(vispDir, "state", "implement-allowed");
const legacyMarkerPath = path.join(vispDir, "state", "implement-allowed.json");
const markers = [];

function unreadableMarker(name) {
  const message =
    \`Visp: implement authorization marker \${name} is unreadable, so task scope is unknown. \` +
    "Re-run \`visp gate implement --task <task-id>\` before committing.";
  if (enforce) block(message);
  writeFileSync(2, \`Warning: \${message}\\n\`);
}

if (existsSync(markerDir)) {
  for (const name of readdirSync(markerDir)) {
    if (!name.endsWith(".json")) continue;
    try {
      const candidate = JSON.parse(readFileSync(path.join(markerDir, name), "utf8"));
      if (typeof candidate === "object" && candidate !== null) markers.push(candidate);
    } catch {
      unreadableMarker(name);
    }
  }
}
if (existsSync(legacyMarkerPath)) {
  try {
    const legacy = JSON.parse(readFileSync(legacyMarkerPath, "utf8"));
    if (
      typeof legacy === "object" &&
      legacy !== null &&
      !markers.some((marker) => marker.taskId === legacy.taskId)
    ) {
      markers.push(legacy);
    }
  } catch {
    unreadableMarker("implement-allowed.json");
  }
}

if (markers.length === 0) {
  const message =
    "Visp: staged source changes have no implement authorization " +
    "(.visp/state/implement-allowed.json missing). " +
    "Run \`visp gate implement --task <task-id>\` and \`visp done --task <task-id>\` before committing.";
  if (enforce) block(message);
  writeFileSync(2, \`Warning: \${message}\\n\`);
  allow();
}

const scopes = markers.map((marker) => [
  ...(marker.allowedFiles ?? []),
  ...(marker.expectedFiles ?? [])
]);
const unrestricted = scopes.some((scope) => scope.length === 0);
const union = scopes.flat();
const forbidden = markers.flatMap((marker) => marker.forbiddenFiles ?? []);
const outOfScope = sourceFiles.filter(
  (file) => forbidden.includes(file) || (!unrestricted && !union.includes(file))
);

if (outOfScope.length > 0) {
  const taskIds = markers.map((marker) => marker.taskId).join(", ");
  const message =
    \`Visp: staged files are outside the scope of active tasks \${taskIds}: \` +
    \`\${outOfScope.join(", ")}. Allowed: \${union.join(", ") || "none declared"}.\`;
  if (enforce) block(message);
  writeFileSync(2, \`Warning: \${message}\\n\`);
}

allow();
`;
}

export function renderPreCommitWrapper(): string {
  return `#!/usr/bin/env bash
# Generated by Visp Kit (visp hooks git). Delegates to the Visp pre-commit check.
set -euo pipefail

if [ -f .visp/hooks/visp-pre-commit.mjs ]; then
  node .visp/hooks/visp-pre-commit.mjs
fi
`;
}

export function renderGithubEvidenceWorkflow(): string {
  return `name: visp-evidence

on:
  pull_request:

jobs:
  evidence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Visp Kit
        run: npm install -g visp-kit
      - name: Validate policy
        run: visp policy validate --json
      - name: Check PR gate
        run: visp gate pr --json
`;
}

export function renderClaudeSettingsSnippet(): string {
  return JSON.stringify(
    {
      hooks: {
        PreToolUse: [
          {
            matcher: "Edit|Write|MultiEdit|NotebookEdit",
            hooks: [
              {
                type: "command",
                command: "node .visp/hooks/claude-pretooluse.mjs"
              }
            ]
          }
        ]
      }
    },
    null,
    2
  );
}

export function renderHooksReadme(): string {
  return `# Visp Kit Enforcement Hooks

These files make Visp gates mechanical instead of advisory. They only enforce
when \`.visp/policy.json\` strictness is \`strict\` or \`locked\`; other modes warn
or stay silent.

Enforcement fails closed: if \`.visp/policy.json\` exists but cannot be parsed,
or declares an unknown strictness mode, the hooks block instead of silently
allowing, because the enforcement state is unknown. A missing policy file
falls back to the non-enforcing \`standard\` default.

## Claude Code PreToolUse hook

\`claude-pretooluse.mjs\` blocks Edit/Write tool calls before
\`visp gate implement --task <task-id>\` has allowed implementation, and blocks
edits outside the task's allowed files.

Enable it by merging this into \`.claude/settings.json\` (or
\`.claude/settings.local.json\`):

\`\`\`json
${renderClaudeSettingsSnippet()}
\`\`\`

## Git pre-commit hook

\`visp-pre-commit.mjs\` checks staged source files against the active task's
implement authorization. Install the wrapper with:

\`\`\`bash
visp hooks git
\`\`\`

## CI evidence check

Generate a GitHub Actions workflow that validates policy and the PR gate on
every pull request:

\`\`\`bash
visp hooks ci
\`\`\`

## How authorization works

\`visp gate implement --task <task-id>\` writes a per-task marker under
\`.visp/state/implement-allowed/<task-id>.json\` (plus the legacy
\`.visp/state/implement-allowed.json\` for hooks generated before per-task
markers existed) when the gate allows implementation. Multiple tasks can hold
authorizations at once; the gate blocks a second task whose file scope
overlaps an active one. \`visp done --task <task-id>\` clears that task's
marker when every step passes, and a blocked implement gate clears it too.

Hooks read every active marker: a file is editable when any active task allows
it and no active task forbids it (forbidden wins). Hooks never call the
network. Markers are per-checkout state — each git worktree has its own — so
parallel agents in separate worktrees do not share authorizations.
`;
}
