export function renderClaudePreToolUseHook(): string {
  return `#!/usr/bin/env node
// Generated by Visp Kit. Blocks Edit/Write tool calls that bypass the Visp implement gate.
// Wire into Claude Code via .claude/settings.json (see .visp/hooks/README.md).
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

function allow() {
  process.exit(0);
}

function block(reason) {
  console.error(reason);
  process.exit(2);
}

let input;
try {
  input = JSON.parse(readFileSync(0, "utf8"));
} catch {
  allow();
}

const editTools = new Set(["Edit", "Write", "MultiEdit", "NotebookEdit"]);
if (!editTools.has(input.tool_name ?? "")) allow();

const filePath = input.tool_input?.file_path ?? input.tool_input?.notebook_path ?? "";
if (filePath === "") allow();

const projectDir = input.cwd ?? process.cwd();
const vispDir = path.join(projectDir, ".visp");
if (!existsSync(vispDir)) allow();

const rel = path.relative(projectDir, path.resolve(projectDir, filePath));
if (rel === "" || rel.startsWith("..")) allow();

const normalized = rel.split(path.sep).join("/");
if (normalized === ".visp" || normalized.startsWith(".visp/")) allow();

let policy;
try {
  policy = JSON.parse(readFileSync(path.join(vispDir, "policy.json"), "utf8"));
} catch {
  allow();
}
if (policy.strictnessMode !== "strict" && policy.strictnessMode !== "locked") allow();

const markerPath = path.join(vispDir, "state", "implement-allowed.json");
if (!existsSync(markerPath)) {
  block(
    "Visp gate: no implement authorization found. Run \`visp gate implement --task <task-id>\` " +
      "and only edit code after it reports allowed."
  );
}

let marker;
try {
  marker = JSON.parse(readFileSync(markerPath, "utf8"));
} catch {
  block(
    "Visp gate: the implement authorization marker is unreadable. " +
      "Re-run \`visp gate implement --task <task-id>\`."
  );
}

const forbidden = marker.forbiddenFiles ?? [];
if (forbidden.includes(normalized)) {
  block(\`Visp gate: \${normalized} is forbidden for task \${marker.taskId}. Do not edit it.\`);
}

const allowed = [...(marker.allowedFiles ?? []), ...(marker.expectedFiles ?? [])];
if (allowed.length > 0 && !allowed.includes(normalized)) {
  block(
    \`Visp gate: \${normalized} is outside the allowed files for task \${marker.taskId} \` +
      \`(allowed: \${allowed.join(", ")}). Edit only allowed files or update the task definition.\`
  );
}

allow();
`;
}

export function renderPreCommitCheck(): string {
  return `#!/usr/bin/env node
// Generated by Visp Kit. Pre-commit evidence check for staged source files.
import { execFileSync } from "node:child_process";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";

function allow() {
  process.exit(0);
}

function block(reason) {
  console.error(reason);
  process.exit(1);
}

const projectDir = process.cwd();
const vispDir = path.join(projectDir, ".visp");
if (!existsSync(vispDir)) allow();

let policy;
try {
  policy = JSON.parse(readFileSync(path.join(vispDir, "policy.json"), "utf8"));
} catch {
  allow();
}

const enforce = policy.strictnessMode === "strict" || policy.strictnessMode === "locked";

let staged;
try {
  staged = execFileSync("git", ["diff", "--cached", "--name-only"], { encoding: "utf8" })
    .split("\\n")
    .map((line) => line.trim())
    .filter((line) => line.length > 0);
} catch {
  allow();
}

const sourceFiles = staged.filter((file) => !file.startsWith(".visp/"));
if (sourceFiles.length === 0) allow();

const markerPath = path.join(vispDir, "state", "implement-allowed.json");
if (!existsSync(markerPath)) {
  const message =
    "Visp: staged source changes have no implement authorization " +
    "(.visp/state/implement-allowed.json missing). " +
    "Run \`visp gate implement --task <task-id>\` and \`visp done --task <task-id>\` before committing.";
  if (enforce) block(message);
  console.warn(\`Warning: \${message}\`);
  allow();
}

let marker;
try {
  marker = JSON.parse(readFileSync(markerPath, "utf8"));
} catch {
  allow();
}

const allowed = [...(marker.allowedFiles ?? []), ...(marker.expectedFiles ?? [])];
const forbidden = marker.forbiddenFiles ?? [];
const outOfScope = sourceFiles.filter(
  (file) => forbidden.includes(file) || (allowed.length > 0 && !allowed.includes(file))
);

if (outOfScope.length > 0) {
  const message =
    \`Visp: staged files are outside the scope of task \${marker.taskId}: \` +
    \`\${outOfScope.join(", ")}. Allowed: \${allowed.join(", ") || "none declared"}.\`;
  if (enforce) block(message);
  console.warn(\`Warning: \${message}\`);
}

allow();
`;
}

export function renderPreCommitWrapper(): string {
  return `#!/usr/bin/env bash
# Generated by Visp Kit (visp hooks git). Delegates to the Visp pre-commit check.
set -euo pipefail

if [ -f .visp/hooks/visp-pre-commit.mjs ]; then
  node .visp/hooks/visp-pre-commit.mjs
fi
`;
}

export function renderGithubEvidenceWorkflow(): string {
  return `name: visp-evidence

on:
  pull_request:

jobs:
  evidence:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Install Visp Kit
        run: npm install -g visp-kit
      - name: Validate policy
        run: visp policy validate --json
      - name: Check PR gate
        run: visp gate pr --json
`;
}

export function renderClaudeSettingsSnippet(): string {
  return JSON.stringify(
    {
      hooks: {
        PreToolUse: [
          {
            matcher: "Edit|Write|MultiEdit|NotebookEdit",
            hooks: [
              {
                type: "command",
                command: "node .visp/hooks/claude-pretooluse.mjs"
              }
            ]
          }
        ]
      }
    },
    null,
    2
  );
}

export function renderHooksReadme(): string {
  return `# Visp Kit Enforcement Hooks

These files make Visp gates mechanical instead of advisory. They only enforce
when \`.visp/policy.json\` strictness is \`strict\` or \`locked\`; other modes warn
or stay silent.

## Claude Code PreToolUse hook

\`claude-pretooluse.mjs\` blocks Edit/Write tool calls before
\`visp gate implement --task <task-id>\` has allowed implementation, and blocks
edits outside the task's allowed files.

Enable it by merging this into \`.claude/settings.json\` (or
\`.claude/settings.local.json\`):

\`\`\`json
${renderClaudeSettingsSnippet()}
\`\`\`

## Git pre-commit hook

\`visp-pre-commit.mjs\` checks staged source files against the active task's
implement authorization. Install the wrapper with:

\`\`\`bash
visp hooks git
\`\`\`

## CI evidence check

Generate a GitHub Actions workflow that validates policy and the PR gate on
every pull request:

\`\`\`bash
visp hooks ci
\`\`\`

## How authorization works

\`visp gate implement --task <task-id>\` writes
\`.visp/state/implement-allowed.json\` when the gate allows implementation.
\`visp done --task <task-id>\` clears it when every step passes. A blocked
implement gate also clears it. Hooks read that marker; they never call the
network.
`;
}
