import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { type ContextPack } from "../../src/artifacts/schemas/context-pack.schema.js";
import {
  understandingCaseExportSchema,
  type UnderstandingCaseExport
} from "../../src/artifacts/schemas/understanding.schema.js";
import { type Task, type TaskGraphArtifact } from "../../src/artifacts/schemas/task.schema.js";
import { contextBudgetPolicy } from "../../src/context/context-budget.js";
import { renderContextMarkdown } from "../../src/context/context-renderer.js";
import { selectContextPack, understandingFilePaths } from "../../src/context/context-selector.js";
import { estimateTokens } from "../../src/context/token-estimator.js";
import { understandingExportObjections } from "../../src/understanding/understanding-export.js";
import { understandingView } from "../../src/understanding/understanding-view.js";
import { type IntelFileGraph } from "../../src/scanner/intel-graph.js";
import { type FileIndexEntry, type FileSummary } from "../../src/scanner/types.js";
import { type ActiveFeature } from "../../src/workflows/shared/active-feature.js";
import { repositoryScanCache } from "../support/repository-scan-cache.js";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

/**
 * Measured on THIS repository, against a REAL intel export.
 *
 * Three things about provenance, because previous versions of this file got
 * two of them wrong and a governance record had to correct one.
 *
 * 1. The scan cache is real, and since this revision it is also REPRODUCIBLE.
 *    It used to be read from `.visp/cache/`, which is gitignored, so all
 *    seventeen tests below passed in a checkout that had run `visp-kit scan`
 *    and failed in every clean clone — and the cache they read was whatever
 *    the last local scan left behind, six days stale when this was found. The
 *    cache is now GENERATED by Kit's own scanner over the tracked files of
 *    this repository, which is the same artifact by the same code path and
 *    depends on nothing but the commit. See `tests/support/`.
 * 2. It is still a real repository and not a fixture in miniature: ~650 files,
 *    which is the shape the 90-135k-token measurement came from. A two-file
 *    fixture cannot show what dominates a pack, so the shape is asserted below
 *    rather than assumed.
 * 3. The understanding case used to be a HAND-WRITTEN literal in this file.
 *    Every number this test printed was therefore a number about a case intel
 *    never produced, and the widely quoted "9,805 -> 2,100 (79%)" was quoted
 *    without that disclosure. The fixture below is a real
 *    `understanding-case-export` artifact, produced by `visp-intel repo index`
 *    + `task scope-proposal` + `understanding export` over this repository at
 *    `ab4cc4e`, and it is validated against Kit's schema and objection rules
 *    before it is used, so a doctored fixture fails the suite rather than
 *    flattering it.
 */
const exportFixturePath = path.join(
  repoRoot,
  "tests",
  "fixtures",
  "understanding",
  "visp-kit-T001.export.json"
);

const feature: ActiveFeature = {
  id: "001",
  slug: "understanding-integration",
  key: "001-understanding-integration",
  path: path.join(repoRoot, ".visp", "features", "001-understanding-integration"),
  relativePath: ".visp/features/001-understanding-integration",
  intent: {
    id: "001",
    slug: "understanding-integration",
    title: "Understanding integration",
    status: "draft",
    budgetMode: "balanced",
    riskLevel: "medium",
    rawUserRequest: "Make the gate read intel's understanding case.",
    createdAt: "2026-01-01T00:00:00.000Z",
    updatedAt: "2026-01-01T00:00:00.000Z"
  }
};

const task: Task = {
  id: "T001",
  title: "Gate behavioural implementation on a current understanding case",
  description:
    "Classify the task, evaluate the understanding conditions, and record the basis in the gate report.",
  requirementIds: [],
  acceptanceCriterionIds: [],
  dependsOn: [],
  allowedFiles: [
    "src/gates/gate-engine.ts",
    "src/gates/stage-checks.ts",
    "src/gates/task-gate-checks.ts",
    "src/context/context-compiler.ts",
    "src/context/context-selector.ts",
    "src/artifacts/schemas/gate.schema.ts"
  ],
  expectedFiles: ["src/gates/understanding-gate.ts"],
  validationCommands: ["pnpm test"],
  status: "ready",
  parallelizable: false,
  riskLevel: "medium",
  taskClass: "cross_file_change",
  riskFactors: []
};

const taskGraph: TaskGraphArtifact = {
  featureId: "001",
  featureSlug: "understanding-integration",
  tasks: [task],
  createdAt: "2026-01-01T00:00:00.000Z",
  updatedAt: "2026-01-01T00:00:00.000Z"
};

async function loadRealExport(): Promise<UnderstandingCaseExport> {
  const raw: unknown = JSON.parse(await readFile(exportFixturePath, "utf8"));
  const parsed = understandingCaseExportSchema.parse(raw);

  // A fixture that Kit itself would refuse as evidence must not be able to
  // stand in for one it would accept.
  expect(understandingExportObjections(parsed)).toEqual([]);

  return parsed;
}

/**
 * The same real case with its path removed.
 *
 * Not an invention: this is the state intel actually returned on 17 of the 29
 * capability-eligible holdout tasks — a current, well-formed case whose scout
 * honestly established nothing. It is the input the old selector handled worst,
 * so it is the one the guarantee is written against.
 */
function withEmptyPath(value: UnderstandingCaseExport): UnderstandingCaseExport {
  return {
    ...value,
    case: { ...value.case, relationIds: [], candidateChangeEntityIds: [] },
    path: [],
    counts: { ...value.counts, pathRelations: 0, candidateChanges: 0 }
  };
}

async function loadScanCache(): Promise<{
  readonly fileIndex: readonly FileIndexEntry[];
  readonly fileSummaries: readonly FileSummary[];
}> {
  return repositoryScanCache(repoRoot);
}

/**
 * A file graph over files that really exist in this repository.
 *
 * Not read from `.visp-intel/`: the projection is built from the working tree
 * and is never committed, both because it is derived state and because a
 * projection frozen as a fixture is the channel through which a holdout task's
 * repository structure could reach a test. The edges below are hand-stated
 * facts about this tree, which is all `collapseToFileGraph` would have produced
 * for them anyway.
 *
 * `src/context/context-relevance.ts` is chosen as the hop-1 file on purpose: it
 * is imported by `context-compiler.ts`, it is a real indexed and summarised
 * file, and the lexical ranking for this task does not select it.
 */
function repositoryFileGraph(): IntelFileGraph {
  const internalEdges = new Map<string, readonly string[]>([
    ["src/context/context-compiler.ts", ["src/context/context-relevance.ts"]],
    ["src/gates/gate-engine.ts", ["src/gates/effective-policy.ts"]],
    // Two hops from the seeds, so it may inform an ordering and may never buy
    // a slot.
    ["src/context/context-relevance.ts", ["src/context/token-estimator.ts"]]
  ]);

  return {
    repositoryInstanceId: "urn:visp-intel:repository-instance:1.0:sha256:visp-kit",
    headSnapshotId: "urn:visp-intel:snapshot:1.0:sha256:head",
    filePaths: [
      "src/context/context-compiler.ts",
      "src/context/context-relevance.ts",
      "src/context/token-estimator.ts",
      "src/gates/effective-policy.ts",
      "src/gates/gate-engine.ts"
    ],
    testFilePaths: [],
    internalEdges,
    externalEdges: new Map(),
    testEdges: new Map()
  };
}

async function packTokens(input: {
  readonly understanding?: UnderstandingCaseExport;
  readonly fileGraph?: IntelFileGraph;
  /**
   * The compact snippet cap. Omitted means the shipped default, which is ON.
   *
   * It used to be impossible to state: the cap fired if and only if an
   * understanding case was present, so "no case" and "no cap" were the same
   * pack and every comparison below silently measured both at once. They are
   * separate inputs now, and the tests that were written against the uncapped
   * baseline say `snippetCap: false` so they keep comparing the two packs they
   * were written to compare.
   */
  readonly snippetCap?: boolean;
}): Promise<{
  readonly tokens: number;
  readonly markdown: string;
  readonly pack: ContextPack;
  readonly onPath: ReadonlySet<string>;
}> {
  const cache = await loadScanCache();
  const understanding =
    input.understanding === undefined
      ? undefined
      : understandingView({
          export: input.understanding,
          current: true,
          currentnessReasons: []
        });
  const pack = await selectContextPack({
    targetPath: repoRoot,
    feature,
    taskGraph,
    task,
    policy: contextBudgetPolicy("balanced", undefined, undefined, input.snippetCap),
    includeFullFiles: false,
    now: "2026-01-01T00:00:00.000Z",
    projectSummary: "Visp Kit is a strict, token-efficient agent harness CLI.",
    patterns: "Layered CLI to workflow to domain to artifacts.",
    fileIndex: cache.fileIndex,
    fileSummaries: cache.fileSummaries,
    ...(understanding === undefined ? {} : { understanding }),
    ...(input.fileGraph === undefined ? {} : { fileGraph: input.fileGraph }),
    warnings: []
  });
  const markdown = renderContextMarkdown({ feature, pack });

  return {
    tokens: estimateTokens(markdown),
    markdown,
    pack,
    onPath: understanding === undefined ? new Set() : understandingFilePaths(understanding)
  };
}

/** Files the pack actually gave the agent something to read. */
function bodiedFiles(pack: ContextPack): ReadonlySet<string> {
  const bodied = new Set<string>();

  for (const file of pack.includedFiles) {
    if ((file.summary ?? "").trim() !== "") bodied.add(file.path);
  }

  for (const snippet of pack.includedSnippets) bodied.add(snippet.filePath);

  return bodied;
}

describe("the compact context pack", () => {
  /**
   * The measurement's other input, guarded.
   *
   * Everything below is a claim about what a pack does over a real repository.
   * Generating the cache instead of reading one removes the ambient-state
   * failure but introduces a new way to be quietly wrong: a scan that returned
   * almost nothing would still let every relative assertion here pass, over a
   * pack with nothing in it to compact. So the shape the claims rest on is
   * asserted, not assumed.
   */
  it("measures against a repository-sized scan, not a handful of files", async () => {
    const cache = await loadScanCache();

    expect(cache.fileIndex.length).toBeGreaterThan(400);
    expect(cache.fileSummaries.length).toBe(cache.fileIndex.length);
    expect(
      cache.fileSummaries.filter((summary) => summary.summarySkippedReason === undefined).length
    ).toBeGreaterThan(400);
    // Nothing untracked reached the cache, which is what makes the printed
    // token count a fact about the commit rather than about this checkout.
    expect(cache.fileIndex.filter((file) => file.path.startsWith(".visp/"))).toEqual([]);
  });

  it("is measured against a real intel export, not a literal written here", async () => {
    const value = await loadRealExport();

    expect(value.kind).toBe("understanding-case-export");
    expect(value.case.authority).toBe("descriptive");
    expect(value.case.authorizationEffect).toBe("none");
    // Produced over a real commit of this repository with a clean worktree.
    expect(value.identity.gitCommit).toMatch(/^[0-9a-f]{40}$/);
    expect(value.identity.dirty).toBe(false);
    expect(value.counts.pathRelations).toBeGreaterThan(0);
  });

  it("shrinks the pack on the same task in the same repository", async () => {
    const before = await packTokens({ snippetCap: false });
    const after = await packTokens({ understanding: await loadRealExport() });

    // Reported, not just asserted: the direction of this number is the phase's
    // central hypothesis, and it has to be readable whichever way it goes.
    // eslint-disable-next-line no-console
    console.log(
      `[P21-KIT-03] context pack input tokens on visp-kit, task T001, REAL intel export: before=${before.tokens} after=${after.tokens} (${Math.round(((before.tokens - after.tokens) / before.tokens) * 100)}% reduction)`
    );

    expect(after.tokens).toBeLessThan(before.tokens);
  });

  /**
   * The same saving, split by what actually produced it.
   *
   * The test above is unchanged in what it compares — an uncapped pack against
   * a pack with a case — and for as long as those were the only two packs Kit
   * could build, it read as "the case shrinks the pack". It does not. Holding
   * the cap fixed on both sides, the case makes the pack BIGGER: it promotes
   * files onto the cited path and adds path-only files, which is what it is
   * for. Every token of the reduction, and then some, is the cap.
   *
   * This is the same shape as the 28-task measurement (cap alone -52.01%
   * against no cap; adding the whole graph pipeline on top costs +19.52%
   * tokens), and it is asserted here so that a change which quietly moves the
   * saving from one mechanism to the other cannot pass.
   */
  it("gets that saving from the cap and not from the case", async () => {
    const uncapped = await packTokens({ snippetCap: false });
    const capped = await packTokens({});
    const cappedWithCase = await packTokens({ understanding: await loadRealExport() });

    // eslint-disable-next-line no-console
    console.log(
      `[cap attribution] visp-kit T001: uncapped=${uncapped.tokens} capped=${capped.tokens} capped+case=${cappedWithCase.tokens}`
    );

    expect(capped.tokens).toBeLessThan(uncapped.tokens);
    expect(cappedWithCase.tokens).toBeGreaterThan(capped.tokens);
  });

  /**
   * The Phase 21 defect, as a property.
   *
   * Path membership used to be a FILTER, so a file the cited path did not name
   * lost its body. Over 29 holdout tasks that cost -78.3% bodied file recall
   * for -66.1% tokens, which is worse value, not better. Path membership is now
   * a RANKING signal, and the guarantee is monotonicity: knowing more about the
   * path never removes something the pack would otherwise have carried.
   *
   * Asserted at BOTH cap settings. Uncapped-with-a-case is a configuration that
   * did not exist while the cap and the case were the same switch, and a
   * guarantee stated in `docs/token-efficiency.md` without qualification has to
   * hold in the configurations the CLI can now produce.
   */
  for (const snippetCap of [true, false]) {
    it(`never bodies fewer files than the same pack with no case at all (cap ${snippetCap ? "on" : "off"})`, async () => {
      const before = await packTokens({ snippetCap });
      const after = await packTokens({ snippetCap, understanding: await loadRealExport() });

      const afterBodied = [...bodiedFiles(after.pack)];

      for (const filePath of bodiedFiles(before.pack)) {
        expect(afterBodied, `${filePath} lost its body to the cited path`).toContain(filePath);
      }
    });
  }

  it("a thin path is never worse than no path", async () => {
    const none = await packTokens({ snippetCap: false });
    const empty = await packTokens({ understanding: withEmptyPath(await loadRealExport()) });

    // The specific defect: a present-but-empty case used to withhold every
    // body while citing a path that did not exist — today's retrieval removed
    // and nothing put in its place.
    expect([...bodiedFiles(empty.pack)].sort()).toEqual([...bodiedFiles(none.pack)].sort());
    expect(empty.tokens).toBeLessThan(none.tokens);
  });

  /**
   * The same guarantee with the cap held fixed, which is the stronger form and
   * was not statable before the cap and the case became separate inputs.
   */
  it("a thin path is never worse than no path at the same cap setting", async () => {
    const none = await packTokens({});
    const empty = await packTokens({ understanding: withEmptyPath(await loadRealExport()) });

    expect([...bodiedFiles(empty.pack)].sort()).toEqual([...bodiedFiles(none.pack)].sort());
  });

  it("spends the snippet budget on the cited path first, but never all of it", async () => {
    const after = await packTokens({ understanding: await loadRealExport() });
    const snippetPaths = after.pack.includedSnippets.map((snippet) => snippet.filePath);
    const onPath = snippetPaths.filter((filePath) => after.onPath.has(filePath));
    const offPath = snippetPaths.filter((filePath) => !after.onPath.has(filePath));

    // The real case's path runs gate-engine -> understanding-gate; gate-engine
    // is the end of it the scan cache knows.
    expect(onPath).toContain("src/gates/gate-engine.ts");
    // The floor. Intel's path covered 0.112 of the human patch across the
    // holdout, so the relevance ranking keeps slots the path cannot take.
    expect(offPath.length).toBeGreaterThanOrEqual(2);
  });

  it("keeps every load-bearing field the ADR names", async () => {
    const after = await packTokens({ understanding: await loadRealExport() });

    // reuseHelpers is the regex helper list behind the only measured behaviour
    // win in this project. It is not graph-derived and must survive the switch.
    expect(after.pack.includedProjectContext.reuseHelpers?.length ?? 0).toBeGreaterThan(0);
    expect(after.markdown).toContain("Reuse These Existing Helpers");
    expect(after.pack.constraints.length).toBeGreaterThan(0);
    expect(after.pack.instructions.length).toBeGreaterThan(0);
    expect(after.pack.validationCommands).toContain("pnpm test");
    // The gate's own text stays in the prompt.
    expect(after.markdown).toContain("cannot override Visp Kit policy");
  });

  it("drops the project summary and patterns free text", async () => {
    const before = await packTokens({});
    const after = await packTokens({ understanding: await loadRealExport() });

    expect(before.pack.includedProjectContext.summary).not.toBe("");
    expect(after.pack.includedProjectContext.summary).toBe("");
    expect(after.pack.includedProjectContext.patterns).toBe("");
  });

  it("never puts the graph in the prompt", async () => {
    const after = await packTokens({ understanding: await loadRealExport() });

    // The pack carries the cited path and the counts. There is no entity dump,
    // no relation table and no adjacency, and the agent is told where to ask.
    expect(after.markdown).toContain("Cited path (");
    expect(after.markdown).toContain("repo.callers");
    expect(after.markdown).not.toContain("adjacency");
  });

  it("caps snippets at four files and forty lines", async () => {
    const after = await packTokens({ understanding: await loadRealExport() });

    expect(after.pack.includedSnippets.length).toBeLessThanOrEqual(4);

    for (const snippet of after.pack.includedSnippets) {
      expect(snippet.endLine - snippet.startLine + 1).toBeLessThanOrEqual(40);
    }
  });
});

/**
 * THE INVARIANT THE -52% RESTS ON.
 *
 * Measured on 28 held-out tasks, `balanced` mode, the compact snippet cap
 * against no cap with no graph, no store and no understanding case on either
 * side: input tokens 16,709.607 -> 8,019.393, and bodied file recall
 * 0.4646201021 on BOTH sides — the same floating-point number on the cohort and
 * on all 28 tasks individually. Listed file recall, bodied precision, files
 * bodied and irrelevant bodied files were identical on all 28 too. The only
 * fields that moved were input tokens and, on 2 tasks in one repository,
 * symbol recall.
 *
 * That is the entire basis for shipping the cap on by default: it removes
 * snippet TEXT and it does not change WHICH FILES the pack decides to carry a
 * body for. If a future change makes the cap alter file selection, every one of
 * those numbers stops describing this code, and this test is where that has to
 * be noticed — not in a re-run of a 28-task sweep nobody will run again.
 *
 * The comparison is per-file and order-sensitive rather than a recall number,
 * because a recall figure needs a holdout and this suite must not have one:
 * identical selections imply identical recall against any ground truth, so the
 * stronger property is also the one that can be asserted from a clean clone.
 */
describe("the compact snippet cap with no understanding case", () => {
  it("changes which files get a body on zero of them", async () => {
    const uncapped = await packTokens({ snippetCap: false });
    const capped = await packTokens({});

    // Neither side may have invented a case to get here: the cap has to be
    // reachable as itself, which is the whole point of the change.
    expect(uncapped.pack.understanding).toBeUndefined();
    expect(capped.pack.understanding).toBeUndefined();
    expect(capped.pack.snippetCapApplied).toBe(true);
    expect(uncapped.pack.snippetCapApplied).toBe(false);

    // The selection, in order. Not a set: position is read downstream.
    expect(capped.pack.includedFiles.map((file) => file.path)).toEqual(
      uncapped.pack.includedFiles.map((file) => file.path)
    );

    // The bodied set — every file the pack gave the agent something to read.
    expect([...bodiedFiles(capped.pack)].sort()).toEqual([...bodiedFiles(uncapped.pack)].sort());

    // And the summaries themselves, verbatim. Symbol-level content rides on
    // these, so "same files" would be a hollow claim if their text moved.
    for (const file of capped.pack.includedFiles) {
      const same = uncapped.pack.includedFiles.find((other) => other.path === file.path);
      expect(same?.summary ?? "").toBe(file.summary ?? "");
    }
  });

  /**
   * The guard against a vacuous invariant.
   *
   * Everything above would pass if the cap became a no-op, and a no-op cap is a
   * silent -52% regression. So: the cap has to actually fire, it has to fire
   * within its stated bounds, and what it removes has to be a SUBSET of what
   * the uncapped pack bodied — the cap deletes snippets, it never substitutes
   * one file's code for another's.
   */
  it("still removes the snippet text, within its stated bounds", async () => {
    const uncapped = await packTokens({ snippetCap: false });
    const capped = await packTokens({});
    const cappedPaths = capped.pack.includedSnippets.map((snippet) => snippet.filePath);
    const uncappedPaths = uncapped.pack.includedSnippets.map((snippet) => snippet.filePath);

    expect(capped.pack.includedSnippets.length).toBeLessThanOrEqual(4);
    expect(capped.pack.includedSnippets.length).toBeLessThan(uncapped.pack.includedSnippets.length);

    for (const snippet of capped.pack.includedSnippets) {
      expect(snippet.endLine - snippet.startLine + 1).toBeLessThanOrEqual(40);
    }

    for (const filePath of cappedPaths) expect(uncappedPaths).toContain(filePath);

    expect(capped.tokens).toBeLessThan(uncapped.tokens);
  });

  /**
   * The cap is not compaction, and must not become it by another route.
   *
   * `compact` — the switch that withholds the project summary and the patterns
   * text — is set by the understanding case and by nothing else, because it is
   * a claim that somebody authored task-scoped evidence. The arm F pack that
   * produced -52.01% carried both of those sections; a cap that also dropped
   * them would be a configuration nobody measured, reported under a number
   * somebody did.
   */
  it("does not withhold anything the case withholds", async () => {
    const capped = await packTokens({});

    expect(capped.pack.includedProjectContext.summary).not.toBe("");
    expect(capped.pack.includedProjectContext.patterns).not.toBe("");
  });
});

/**
 * The second seam.
 *
 * The graph has reached scan's module map since `197e329` and the context pack
 * was bit-identical with and without it, because nothing downstream read the
 * map. These are the properties that must hold now that the selector does read
 * the graph — and every one of them is a bound on what the graph is allowed to
 * do, not a claim about how much it helps. Whether it helps is a measurement,
 * and this file cannot make one.
 */
describe("the graph conditions retrieval", () => {
  const graphed = () => packTokens({ fileGraph: repositoryFileGraph() });

  it("changes the pack, which is the thing that was not true before", async () => {
    const without = await packTokens({});
    const with_ = await graphed();

    expect(with_.pack.includedFiles.length).toBeGreaterThan(without.pack.includedFiles.length);
  });

  /**
   * MONOTONICITY, in its strongest form: the no-graph file list is a PREFIX of
   * the graphed one. Not merely a superset — an order-preserving extension, so
   * nothing that reads position sees a different answer for a file that was
   * already there. A signal that can take a file's body away is deciding what
   * the model may not see, and that is the one power that stays out.
   */
  it("only ever appends, so no file loses its body to a graph fact", async () => {
    const without = await packTokens({});
    const with_ = await graphed();
    const before = without.pack.includedFiles.map((file) => file.path);
    const after = with_.pack.includedFiles.map((file) => file.path);

    expect(after.slice(0, before.length)).toEqual(before);
  });

  it("admits at most two files, and only at one hop", async () => {
    const without = await packTokens({});
    const with_ = await graphed();
    const before = new Set(without.pack.includedFiles.map((file) => file.path));
    const admitted = with_.pack.includedFiles
      .map((file) => file.path)
      .filter((filePath) => !before.has(filePath));

    expect(admitted).toEqual(["src/context/context-relevance.ts", "src/gates/effective-policy.ts"]);
    // Two hops from a seed is "something that talks to something the task
    // touches", which is true of most of a codebase. It never buys a slot.
    expect(admitted).not.toContain("src/context/token-estimator.ts");
  });

  it("buys summaries and never the expensive slots", async () => {
    const without = await packTokens({});
    const with_ = await graphed();

    // `allocateSnippets` is handed exactly the list it would have been handed
    // with no graph, so the reserved relevance floor and the path budget are
    // arithmetically untouched.
    expect(with_.pack.includedSnippets).toEqual(without.pack.includedSnippets);

    for (const file of with_.pack.includedFiles) {
      if (file.reason.startsWith("One import or test hop")) {
        expect(file.snippetIncluded).toBe(false);
        expect((file.summary ?? "").trim()).not.toBe("");
      }
    }
  });

  /**
   * The one new constraint the understanding case did not need.
   *
   * Compaction WITHHOLDS file bodies and fires on the presence of a case. The
   * case is task-scoped and has to be authored per task; the projection is
   * repository-wide and present on every task after one index. If the graph
   * could set `compact`, indexing a repository once would shrink every pack in
   * it forever with no per-task evidence behind any of them.
   */
  it("cannot put the pack into compact mode", async () => {
    const with_ = await graphed();

    expect(with_.pack.includedProjectContext.summary).not.toBe("");
    expect(with_.pack.includedProjectContext.patterns).not.toBe("");
    expect(with_.pack.understanding).toBeUndefined();
  });

  it("costs summaries, not snippets, so the pack grows by a bounded amount", async () => {
    const without = await packTokens({});
    const with_ = await graphed();

    // Two ~300-token summaries against a pack this size. The bound asserted
    // here is the mechanism's, not a measurement: Dev owns the number.
    expect(with_.tokens).toBeGreaterThan(without.tokens);
    expect(with_.tokens).toBeLessThan(without.tokens * 1.15);
  });

  it("degrades to today's pack when the graph reaches nothing", async () => {
    const without = await packTokens({});
    const disconnected = await packTokens({
      fileGraph: {
        ...repositoryFileGraph(),
        internalEdges: new Map([["docs/unrelated.md", ["docs/other.md"]]]),
        testEdges: new Map()
      }
    });

    expect(disconnected.pack).toEqual(without.pack);
    expect(disconnected.markdown).toEqual(without.markdown);
  });

  it("still admits nothing the pack was already forbidden to carry", async () => {
    const with_ = await graphed();
    const admittedButUnindexed = with_.pack.includedFiles.filter(
      (file) => file.reason.startsWith("One import or test hop") && file.includeMode === "new-file"
    );

    // Structural admission goes through the same `isEligible` join as every
    // other candidate: indexed, not forbidden, not ignored, not binary, not a
    // lockfile. A file the graph names and scan has never seen is not a file.
    expect(admittedButUnindexed).toEqual([]);
  });

  it("layers on top of the cited path rather than competing with it", async () => {
    const understanding = await loadRealExport();
    const caseOnly = await packTokens({ understanding });
    const both = await packTokens({ understanding, fileGraph: repositoryFileGraph() });
    const before = caseOnly.pack.includedFiles.map((file) => file.path);

    expect(both.pack.includedFiles.map((file) => file.path).slice(0, before.length)).toEqual(
      before
    );
    expect(both.pack.includedSnippets).toEqual(caseOnly.pack.includedSnippets);
  });
});
