import { execFile, spawn } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";

import { afterEach, beforeEach, describe, expect, it } from "vitest";

import { createCli } from "../../src/cli/main.js";
import { pathExists } from "../../src/core/file-system.js";
import { runInitWorkflow } from "../../src/workflows/init.workflow.js";
import { createPhase8Fixture, expectOk } from "./phase8-fixture.js";

const execFileAsync = promisify(execFile);

async function exists(filePath: string): Promise<boolean> {
  return expectOk(await pathExists(filePath));
}

type HookRun = {
  readonly exitCode: number;
  readonly stderr: string;
};

async function runClaudeHookWithStdin(rootPath: string, hookInput: unknown): Promise<HookRun> {
  const hookPath = path.join(rootPath, ".visp", "hooks", "claude-pretooluse.mjs");

  return new Promise((resolve) => {
    const child = spawn("node", [hookPath], { cwd: rootPath });
    let stderr = "";

    child.stderr.on("data", (chunk: Buffer) => {
      stderr += chunk.toString();
    });
    child.on("close", (code: number | null) => {
      resolve({ exitCode: code ?? 0, stderr });
    });
    child.stdin.write(JSON.stringify({ cwd: rootPath, ...(hookInput as object) }));
    child.stdin.end();
  });
}

describe("visp hooks command", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await mkdtemp(path.join(os.tmpdir(), "visp-hooks-command-"));
    process.exitCode = undefined;
  });

  afterEach(async () => {
    process.exitCode = undefined;
    await rm(tempDir, { recursive: true, force: true });
  });

  it("installs the claude hook and prints the settings snippet", async () => {
    expectOk(await runInitWorkflow({ targetPath: tempDir, agent: "none" }));
    const output: string[] = [];
    const program = createCli({ writeOut: (value) => output.push(value) });

    await program.parseAsync(["node", "visp", "hooks", "claude", tempDir]);

    expect(await exists(path.join(tempDir, ".visp", "hooks", "claude-pretooluse.mjs"))).toBe(true);
    expect(await exists(path.join(tempDir, ".visp", "hooks", "README.md"))).toBe(true);
    expect(output.join("")).toContain("PreToolUse");
    expect(output.join("")).toContain("node .visp/hooks/claude-pretooluse.mjs");
  });

  it("installs the git pre-commit hook in a git repository", async () => {
    expectOk(await runInitWorkflow({ targetPath: tempDir, agent: "none" }));
    await execFileAsync("git", ["init"], { cwd: tempDir });
    const program = createCli({ writeOut: () => undefined });

    await program.parseAsync(["node", "visp", "hooks", "git", tempDir]);

    const wrapperPath = path.join(tempDir, ".git", "hooks", "pre-commit");

    expect(await exists(path.join(tempDir, ".visp", "hooks", "visp-pre-commit.mjs"))).toBe(true);
    expect(await exists(wrapperPath)).toBe(true);
    expect(await readFile(wrapperPath, "utf8")).toContain("Generated by Visp Kit");
  });

  it("does not overwrite a foreign pre-commit hook without force", async () => {
    expectOk(await runInitWorkflow({ targetPath: tempDir, agent: "none" }));
    await execFileAsync("git", ["init"], { cwd: tempDir });
    const hookPath = path.join(tempDir, ".git", "hooks", "pre-commit");
    await mkdir(path.dirname(hookPath), { recursive: true });
    await writeFile(hookPath, "#!/bin/sh\necho custom hook\n", "utf8");

    const output: string[] = [];
    const program = createCli({ writeOut: (value) => output.push(value) });

    await program.parseAsync(["node", "visp", "hooks", "git", tempDir, "--json"]);

    const summary = JSON.parse(output.join("")) as {
      warnings: string[];
      skippedFiles: string[];
    };

    expect(summary.warnings.join(" ")).toContain("was not generated by Visp Kit");
    expect(await readFile(hookPath, "utf8")).toContain("custom hook");
  });

  it("generates the CI evidence workflow", async () => {
    expectOk(await runInitWorkflow({ targetPath: tempDir, agent: "none" }));
    const program = createCli({ writeOut: () => undefined });

    await program.parseAsync(["node", "visp", "hooks", "ci", tempDir]);

    const workflowPath = path.join(tempDir, ".github", "workflows", "visp-evidence.yml");

    expect(await exists(workflowPath)).toBe(true);
    const contents = await readFile(workflowPath, "utf8");
    expect(contents).toContain("visp policy validate --json");
    expect(contents).toContain("visp gate pr --json");
  });

  it("dry-run writes nothing", async () => {
    expectOk(await runInitWorkflow({ targetPath: tempDir, agent: "none" }));
    const program = createCli({ writeOut: () => undefined });

    await program.parseAsync(["node", "visp", "hooks", "ci", tempDir, "--dry-run"]);

    expect(await exists(path.join(tempDir, ".github", "workflows", "visp-evidence.yml"))).toBe(
      false
    );
  });

  it("fails clearly when .visp is missing", async () => {
    const errors: string[] = [];
    const program = createCli({ writeErr: (value) => errors.push(value) });

    await program.parseAsync(["node", "visp", "hooks", "git", tempDir]);

    expect(process.exitCode).toBe(1);
    expect(errors.join("")).toContain("visp init");
  });
});

describe("claude pretooluse hook script", () => {
  let tempDir: string;

  beforeEach(async () => {
    tempDir = await mkdtemp(path.join(os.tmpdir(), "visp-claude-hook-"));
    process.exitCode = undefined;
  });

  afterEach(async () => {
    process.exitCode = undefined;
    await rm(tempDir, { recursive: true, force: true });
  });

  async function installStrictFixtureWithHook(): Promise<void> {
    await createPhase8Fixture(tempDir);
    const program = createCli({ writeOut: () => undefined });

    await program.parseAsync(["node", "visp", "policy", "set-strictness", "strict", tempDir]);
    await program.parseAsync(["node", "visp", "hooks", "claude", tempDir]);
  }

  it("blocks source edits when no implement marker exists", async () => {
    await installStrictFixtureWithHook();

    const result = await runClaudeHookWithStdin(tempDir, {
      tool_name: "Edit",
      tool_input: { file_path: "src/notes.ts" }
    });

    expect(result.exitCode).toBe(2);
    expect(result.stderr).toContain("visp gate implement");
  });

  it("allows edits to .visp artifacts and non-edit tools", async () => {
    await installStrictFixtureWithHook();

    const vispEdit = await runClaudeHookWithStdin(tempDir, {
      tool_name: "Edit",
      tool_input: { file_path: ".visp/notes.md" }
    });
    const bash = await runClaudeHookWithStdin(tempDir, {
      tool_name: "Bash",
      tool_input: { command: "ls" }
    });

    expect(vispEdit.exitCode).toBe(0);
    expect(bash.exitCode).toBe(0);
  });

  it("allows edits inside allowed files after the gate writes the marker", async () => {
    await installStrictFixtureWithHook();
    const program = createCli({ writeOut: () => undefined });

    await program.parseAsync(["node", "visp", "context", "T001", tempDir, "--force"]);
    await program.parseAsync(["node", "visp", "gate", "implement", tempDir, "--task", "T001"]);

    const markerPath = path.join(tempDir, ".visp", "state", "implement-allowed.json");

    expect(await exists(markerPath)).toBe(true);

    const marker = JSON.parse(await readFile(markerPath, "utf8")) as {
      taskId: string;
      allowedFiles: string[];
    };

    expect(marker.taskId).toBe("T001");
    expect(marker.allowedFiles.length).toBeGreaterThan(0);

    const allowedFile = marker.allowedFiles[0]!;
    const allowedEdit = await runClaudeHookWithStdin(tempDir, {
      tool_name: "Edit",
      tool_input: { file_path: allowedFile }
    });
    const outsideEdit = await runClaudeHookWithStdin(tempDir, {
      tool_name: "Write",
      tool_input: { file_path: "src/unrelated-module.ts" }
    });

    expect(allowedEdit.exitCode).toBe(0);
    expect(outsideEdit.exitCode).toBe(2);
    expect(outsideEdit.stderr).toContain("outside the allowed files");
  });

  it("stays silent in relaxed and standard strictness", async () => {
    await createPhase8Fixture(tempDir);
    const program = createCli({ writeOut: () => undefined });
    await program.parseAsync(["node", "visp", "hooks", "claude", tempDir]);

    const result = await runClaudeHookWithStdin(tempDir, {
      tool_name: "Edit",
      tool_input: { file_path: "src/notes.ts" }
    });

    expect(result.exitCode).toBe(0);
  });
});
