import { type PrArtifact } from "../artifacts/schemas/pr.schema.js";
import { renderPolicyGateMarkdown } from "../gates/policy-gate-markdown.js";

function list(values: readonly string[], empty = "- None."): string {
  return values.length === 0 ? empty : values.map((value) => `- ${value}`).join("\n");
}

export function renderPrMarkdown(pr: PrArtifact): string {
  const requirements = pr.requirementsCovered
    .map((item) =>
      `| ${item.requirementId} | ${item.acceptanceCriterionIds.join(", ") || "none"} | ${item.status} |`
    )
    .join("\n");
  const tasks = pr.tasksIncluded
    .map((task) =>
      `| ${task.taskId} | ${task.status} | ${task.evidence.join(", ") || "missing"} |`
    )
    .join("\n");
  const files = pr.changedFiles
    .map((file) => `| ${file.path} | ${file.changeType} | ${file.notes} |`)
    .join("\n");
  const checklistItems = pr.implementationChecklist.items
    .map((item) => `| ${item.id} | ${item.status} | ${item.required ? "yes" : "no"} | ${item.evidence ?? ""} | ${item.reason ?? ""} |`)
    .join("\n");

  return `# Pull Request: ${pr.title}

## Summary

${pr.summary}

## Feature

- Feature: ${pr.featureId}-${pr.featureSlug}
- Status: ${pr.success ? pr.reconcileEvidence.status : "blocked"}

## Policy Readiness

${renderPolicyGateMarkdown(pr.policyGate)}

## Requirements Covered

| Requirement | Acceptance Criteria | Status |
|-------------|---------------------|--------|
${requirements || "| none | none | missing |"}

## Tasks Included

| Task | Status | Evidence |
|------|--------|----------|
${tasks || "| none | missing | missing |"}

## Changes

| File | Change | Notes |
|------|--------|-------|
${files || "| none | unknown | no Git diff available |"}

## Validation

- Verification: ${pr.validationEvidence.status}
- Review: ${pr.reviewEvidence.status}
- Reconcile: ${pr.reconcileEvidence.status}
- Implementation checklist: ${pr.implementationChecklist.status}
- Actual usage: ${pr.usage.status}

Commands run:
${list(pr.validationEvidence.summary.filter((item) => item.startsWith("Command run:")).map((item) => item.replace("Command run: ", "")))}

## Actual Token Usage

- Status: ${pr.usage.status}
- Input: ${pr.usage.status === "unavailable" ? "unavailable" : pr.usage.inputTokens ?? "not recorded"}
- Output: ${pr.usage.status === "unavailable" ? "unavailable" : pr.usage.outputTokens ?? "not recorded"}
- Total: ${pr.usage.status === "unavailable" ? "unavailable" : pr.usage.totalTokens ?? "not recorded"}
- Source: ${pr.usage.source ?? "none"}
- Model: ${pr.usage.model ?? "none"}
- Recorded: ${pr.usage.recordedAt ?? "none"}
- Note: ${pr.usage.note ?? "none"}

## Risk and Rollback

Risk:
${list(pr.risks)}

Rollback:
${list(pr.rollback)}

## Checklist

${pr.checklist.map((item) => `- [ ] ${item}`).join("\n")}

## Implementation Checklist Evidence

Status: ${pr.implementationChecklist.status}

Pending required: ${pr.implementationChecklist.pendingRequiredIds.join(", ") || "none"}
Blocked required: ${pr.implementationChecklist.blockedRequiredIds.join(", ") || "none"}
Usage status: ${pr.implementationChecklist.usageStatus}

| Item | Status | Required | Evidence | Reason |
|------|--------|----------|----------|--------|
${checklistItems || "| none | missing | no |  |  |"}

## Follow-up Work

${list(pr.followUps)}

## Warnings

${list(pr.warnings)}

## Generated By

Visp Kit
`;
}
