import { type PrArtifact } from "../artifacts/schemas/pr.schema.js";
import { renderPolicyGateMarkdown } from "../gates/policy-gate-markdown.js";

function list(values: readonly string[], empty = "- None."): string {
  return values.length === 0 ? empty : values.map((value) => `- ${value}`).join("\n");
}

export function renderPrMarkdown(pr: PrArtifact): string {
  const requirements = pr.requirementsCovered
    .map((item) =>
      `| ${item.requirementId} | ${item.acceptanceCriterionIds.join(", ") || "none"} | ${item.status} |`
    )
    .join("\n");
  const tasks = pr.tasksIncluded
    .map((task) =>
      `| ${task.taskId} | ${task.status} | ${task.evidence.join(", ") || "missing"} |`
    )
    .join("\n");
  const files = pr.changedFiles
    .map((file) => `| ${file.path} | ${file.changeType} | ${file.notes} |`)
    .join("\n");

  return `# Pull Request: ${pr.title}

## Summary

${pr.summary}

## Feature

- Feature: ${pr.featureId}-${pr.featureSlug}
- Status: ${pr.success ? pr.reconcileEvidence.status : "blocked"}

## Policy Readiness

${renderPolicyGateMarkdown(pr.policyGate)}

## Requirements Covered

| Requirement | Acceptance Criteria | Status |
|-------------|---------------------|--------|
${requirements || "| none | none | missing |"}

## Tasks Included

| Task | Status | Evidence |
|------|--------|----------|
${tasks || "| none | missing | missing |"}

## Changes

| File | Change | Notes |
|------|--------|-------|
${files || "| none | unknown | no Git diff available |"}

## Validation

- Verification: ${pr.validationEvidence.status}
- Review: ${pr.reviewEvidence.status}
- Reconcile: ${pr.reconcileEvidence.status}

Commands run:
${list(pr.validationEvidence.summary.filter((item) => item.startsWith("Command run:")).map((item) => item.replace("Command run: ", "")))}

## Risk and Rollback

Risk:
${list(pr.risks)}

Rollback:
${list(pr.rollback)}

## Checklist

${pr.checklist.map((item) => `- [ ] ${item}`).join("\n")}

## Follow-up Work

${list(pr.followUps)}

## Warnings

${list(pr.warnings)}

## Generated By

Visp Kit
`;
}
